// Automatically generated from Google Sheets data
import { MenuItem } from './restaurant';

export const MENU_ITEMS: MenuItem[] = [
  {
    "id": "item_1",
    "name": "Lemon juice / Lemon mint juice",
    "nameBn": "লেবুর রস / লেবু মিন্ট জুস",
    "description": "A very refreshing and satisfying drink made with a blend of fresh lime juice and fragrant mint leaves.",
    "descriptionBn": "তাজা পাতিলেবুর রস এবং সুগন্ধি পুদিনা পাতার মিশ্রণে তৈরি এক অত্যন্ত সতেজ ও তৃপ্তিদায়ক পানীয়।",
    "price": 40,
    "category": "JUICE",
    "image": "https://drive.google.com/thumbnail?id=1Osg1Y0N7OBgQU-t41zKmwyMj1wUkp2Sp&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_2",
    "name": "Lemon soda / Lemon mint soda",
    "nameBn": "লেমন সোডা/ লেমন মিন্ট সোডা",
    "description": "Sparkling soda water pairs perfectly with the zesty flavors of lemon and mint, which instantly invigorates.",
    "descriptionBn": "ঝলমলে সোডা ওয়াটারের সাথে পাতিলেবু ও পুদিনার চনমনে স্বাদের চমৎকার জুড়ি, যা মুহূর্তেই প্রাণ জুড়িয়ে দেয়।",
    "price": 40,
    "category": "JUICE",
    "image": "https://drive.google.com/thumbnail?id=1sqCFl3P1PAonU6_Tdo9CXGKoSujYOPE_&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_3",
    "name": "Masala cold Drink",
    "nameBn": "মসলা ঠান্ডা পানীয়",
    "description": "A unique blend of crisp Indian spices and cold drinks, which brings a magical surprise to the taste buds.",
    "descriptionBn": "চটপটা ভারতীয় মশলা ও ঠান্ডা পানীয়ের এক অনন্য মিশ্রণ, যা স্বাদে এনে দেয় এক জাদুকরী চমক।",
    "price": 55,
    "category": "JUICE",
    "image": "https://drive.google.com/thumbnail?id=1EZWcKjLj5gxaSbScvNGNu-t3gERpjT-I&sz=w800",
    "isPopular": false,
    "isBestSeller": true,
    "isHighestRated": false
  },
  {
    "id": "item_4",
    "name": "Haveli Fizz",
    "nameBn": "হাভেলি ফিজ",
    "description": "A royal and delicious mocktail made with our own special recipe, which gives every sip a refreshing sensation.",
    "descriptionBn": "আমাদের নিজস্ব বিশেষ রেসিপিতে তৈরি এক রাজকীয় ও চনমনে মকটেল, যা প্রতি চুমুকেই দেয় এক সতেজ অনুভূতি।",
    "price": 99,
    "category": "MOCKTAIL",
    "image": "https://drive.google.com/thumbnail?id=1s9spe0qtYjkXSxWbA_pxz1u6XNqp89lg&sz=w800",
    "isPopular": true,
    "isBestSeller": false,
    "isHighestRated": true
  },
  {
    "id": "item_5",
    "name": "Ice Tea",
    "nameBn": "বরফ চা",
    "description": "The mildly sweet and lemony aroma of ice cold tea is perfect for de-stressing.",
    "descriptionBn": "বরফ শীতল চায়ের সাথে হালকা মিষ্টি ও লেবুর সুবাস, ক্লান্তি দূর করার জন্য একদম উপযুক্ত।",
    "price": 99,
    "category": "MOCKTAIL",
    "image": "https://drive.google.com/thumbnail?id=16RH-9eKDrNjRRQPsm0d94d70rnYUwNRg&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_6",
    "name": "Lichi Sparkler",
    "nameBn": "লিচি স্পার্কলার",
    "description": "A wonderful and refreshing pairing of sweet lychee extract and bubbly sparkling water.",
    "descriptionBn": "মিষ্টি লিচুর নির্যাস এবং বাবলি স্পার্কলিং ওয়াটারের এক দুর্দান্ত ও রিফ্রেশিং যুগলবন্দী।",
    "price": 79,
    "category": "MOCKTAIL",
    "image": "https://drive.google.com/thumbnail?id=1dxCUPLufxVs4_SRfhzNEsyumRYEVj13Z&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_7",
    "name": "Virgin Mojito",
    "nameBn": "ভার্জিন মোজিটো",
    "description": "Crushed ice, fresh mint leaves, lime and soda is a classic and evergreen refreshing drink.",
    "descriptionBn": "ক্রাশড আইস, তাজা পুদিনা পাতা, পাতিলেবু ও সোডার এক ক্লাসিক এবং চিরসবুজ সতেজ পানীয়।",
    "price": 79,
    "category": "MOCKTAIL",
    "image": "https://drive.google.com/thumbnail?id=18CNRB3r3NlxEHo3qqT7kgvvcUlVfDZru&sz=w800",
    "isPopular": true,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_8",
    "name": "Blue Berry Mojito",
    "nameBn": "ব্লু বেরি মোজিটো",
    "description": "An enticing blue drink made with the sweet and sour flavors of ripe blueberries, mint and lemon.",
    "descriptionBn": "পাকা ব্লুবেরির মিষ্টি ও টক স্বাদ, পুদিনা এবং লেবুর সাথে মিশে তৈরি এক লোভনীয় নীল রঙের পানীয়।",
    "price": 99,
    "category": "MOCKTAIL",
    "image": "https://drive.google.com/thumbnail?id=1X3fpLvv_EQwDjG0xyptvzpXfMEo8C1Y2&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_9",
    "name": "Litchi Mojito",
    "nameBn": "লিচু মোজিটো",
    "description": "A wonderful combination of the sweet taste of juicy lychee and the freshness of mint-lemon.",
    "descriptionBn": "রসালো লিচুর মিষ্টি স্বাদ ও পুদিনা-লেবুর সতেজতার এক অপূর্ব সমন্বয়।",
    "price": 99,
    "category": "MOCKTAIL",
    "image": "https://drive.google.com/thumbnail?id=1_hpx_F4e3hB_gFynZqibMxYmr2AY_9A5&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_10",
    "name": "Strawberry Mojito",
    "nameBn": "স্ট্রবেরি মোজিটো",
    "description": "A sweet and fruity drink made with a blend of ripe red strawberries, fresh mint and soda.",
    "descriptionBn": "পাকা লাল স্ট্রবেরি, তাজা পুদিনা এবং সোডার মিশ্রণে তৈরি এক মিষ্টি ও ফ্রুটি পানীয়।",
    "price": 99,
    "category": "MOCKTAIL",
    "image": "https://drive.google.com/thumbnail?id=1NL61288HkZl8isw8gS6-OlbgavQnGl_G&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_11",
    "name": "Water Milon Mojito",
    "nameBn": "জল মিলন মোজিটো",
    "description": "Juicy summer watermelon and cold soda is a very satisfying and refreshing drink.",
    "descriptionBn": "গ্রীষ্মের রসালো তরমুজ ও ঠান্ডা সোডার এক দারুণ তৃপ্তিদায়ক এবং মন ভালো করা পানীয়।",
    "price": 99,
    "category": "MOCKTAIL",
    "image": "https://drive.google.com/thumbnail?id=1OtAPj46Qdf76Y0b6gS-5IT9r0ubY1zsX&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_12",
    "name": "Green Apple Mojito",
    "nameBn": "সবুজ আপেল মোজিটো",
    "description": "A lively mocktail filled with the mild sour-sweet taste of raw apples and the freshness of mint.",
    "descriptionBn": "কাঁচা আপেলের হালকা টক-মিষ্টি স্বাদ এবং পুদিনার সতেজতায় ভরা এক প্রাণবন্ত মকটেল।",
    "price": 99,
    "category": "MOCKTAIL",
    "image": "https://drive.google.com/thumbnail?id=1LHYCqo-fPAirkTkiUcj7AnWVx7W0eSDK&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": true
  },
  {
    "id": "item_13",
    "name": "Vanilla (S/D)",
    "nameBn": "ভ্যানিলা (S/D)",
    "description": "A soft, creamy and delicious classic ice cream infused with the aroma of pure vanilla beans.",
    "descriptionBn": "খাঁটি ভ্যানিলা বিনের সুবাসে ভরা এক নরম, ক্রিমি এবং সুস্বাদু ক্লাসিক আইসক্রিম।",
    "price": 40,
    "category": "ICE-CREAM",
    "image": "https://drive.google.com/thumbnail?id=186XeHg00nVqI3JhesP-SnoUqpFzPhkVo&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_14",
    "name": "Strawberry (S/D)",
    "nameBn": "স্ট্রবেরি (S/D)",
    "description": "A pink and creamy cold ice cream with sweet strawberry flavor, loved by kids and adults alike.",
    "descriptionBn": "মিষ্টি স্ট্রবেরি ফ্লেভারের এক গোলাপি ও ক্রিমি ঠান্ডা আইসক্রিম, যা বাচ্চাদের এবং বড়দের সমান প্রিয়।",
    "price": 40,
    "category": "ICE-CREAM",
    "image": "https://drive.google.com/thumbnail?id=1o1Z3ZtyIrL798JmaZ4HPUxfjthySJBZO&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_15",
    "name": "Chocolate (S/D)",
    "nameBn": "চকোলেট (S/D)",
    "description": "A luscious ice cream made with thick and rich chocolate, perfect for chocolate lovers.",
    "descriptionBn": "ঘন ও সমৃদ্ধ চকোলেটে তৈরি এক লোভনীয় আইসক্রিম, চকোলেট প্রেমীদের জন্য একদম পারফেক্ট।",
    "price": 40,
    "category": "ICE-CREAM",
    "image": "https://drive.google.com/thumbnail?id=1WWjYJc6zhxUi7Iha7yc2kTxLE7npcH5t&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_16",
    "name": "Mango (S/D)",
    "nameBn": "আম (S/D)",
    "description": "A creamy and summery ice cream packed with the sweet taste of ripe mangoes.",
    "descriptionBn": "পাকা আমের মিষ্টি স্বাদে ভরপুর এক ক্রিমি ও গ্রীষ্মকালীন বিশেষ আইসক্রিম।",
    "price": 40,
    "category": "ICE-CREAM",
    "image": "https://drive.google.com/thumbnail?id=1upWjRu4YG6t0uVjTziIz8REXZpY9eZ7l&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_17",
    "name": "Butter Scotch (S/D)",
    "nameBn": "বাটার স্কচ (S/D)",
    "description": "A creamy butterscotch ice cream with caramel and chunks of almonds.",
    "descriptionBn": "ক্যারামেল এবং মুচমুচে বাদামের টুকরোর সাথে ক্রিমি বাটার স্কচের এক অসাধারণ স্বাদের আইসক্রিম।",
    "price": 45,
    "category": "ICE-CREAM",
    "image": "https://drive.google.com/thumbnail?id=1Ou8UwewJgU_YZJhiUFT7e9oaySe39VZj&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_18",
    "name": "Black Currant (S/D)",
    "nameBn": "কালো কারেন্ট (S/D)",
    "description": "An exotic and delicious ice cream with chunks of sweet and mildly sour black currant berries.",
    "descriptionBn": "মিষ্টি ও হালকা টক ব্ল্যাক কারেন্ট বেরির টুকরো সম্বলিত এক এক্সটিক এবং সুস্বাদু আইসক্রিম।",
    "price": 45,
    "category": "ICE-CREAM",
    "image": "https://drive.google.com/thumbnail?id=1HRgm9oxu_EhqPnHIY1uNJrrs9JFfhvdd&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_19",
    "name": "3 in 1",
    "nameBn": "1 তে 3",
    "description": "A wonderful and creamy combination of three popular flavors—vanilla, strawberry, and chocolate.",
    "descriptionBn": "ভ্যানিলা, স্ট্রবেরি ও চকোলেট—এই তিনটি জনপ্রিয় ফ্লেভারের এক দুর্দান্ত এবং ক্রিমি মেলবন্ধন।",
    "price": 120,
    "category": "ICE-CREAM",
    "image": "https://drive.google.com/thumbnail?id=1VXFk7Xu8xbYlqh2sKynRt7-mK7e681ON&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_20",
    "name": "Vanilla Shake",
    "nameBn": "ভ্যানিলা শেক",
    "description": "A very tasty and nutritious milkshake made with a mixture of condensed milk and creamy vanilla ice cream.",
    "descriptionBn": "ঘন দুধ এবং ক্রিমি ভ্যানিলা আইসক্রিমের মিশ্রণে তৈরি এক অতি সুস্বাদু ও পুষ্টিকর মিল্কশেক।",
    "price": 99,
    "category": "MILK SHAKE",
    "image": "https://drive.google.com/thumbnail?id=1BLWvUESPL3viEOauw9M_xHo_nLc571ek&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_21",
    "name": "Strawberry Shake",
    "nameBn": "স্ট্রবেরি শেক",
    "description": "A sweet and creamy pink shake made with a blend of fresh strawberry flavor and cold milk.",
    "descriptionBn": "তাজা স্ট্রবেরি ফ্লেভার এবং ঠান্ডা দুধের মিশ্রণে তৈরি এক মিষ্টি ও ক্রিমি গোলাপি শেক।",
    "price": 99,
    "category": "MILK SHAKE",
    "image": "https://drive.google.com/thumbnail?id=1jGtFv4Y8GwgI347NzgjbKk4VQ6z7kC6u&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_22",
    "name": "Chocolate Shake",
    "nameBn": "চকোলেট শেক",
    "description": "A great chocolaty and energizing drink of thick chocolate syrup, ice cream and milk.",
    "descriptionBn": "ঘন চকোলেট সিরাপ, আইসক্রিম ও দুধের এক দুর্দান্ত চকোলেটি এবং এনার্জিটিক পানীয়।",
    "price": 99,
    "category": "MILK SHAKE",
    "image": "https://drive.google.com/thumbnail?id=1tvyE6aa55-CmXjcfW6pXEvfWANL-lCQw&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_23",
    "name": "Mango Shake",
    "nameBn": "ম্যাঙ্গো শেক",
    "description": "A hearty summer milkshake made with a mixture of ripe mango pulp and condensed milk.",
    "descriptionBn": "পাকা আমের পাল্প ও ঘন দুধের মিশ্রণে তৈরি এক মন জুড়ানো গ্রীষ্মকালীন মিল্কশেক।",
    "price": 99,
    "category": "MILK SHAKE",
    "image": "https://drive.google.com/thumbnail?id=1uk20eO35CXE1diWxSVvrnIQ-Cq6VEVct&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_24",
    "name": "Butter Scotch shake",
    "nameBn": "বাটার স্কচ শেক",
    "description": "A royal and thick milkshake mixed with butterscotch ice cream and caramel crunch.",
    "descriptionBn": "বাটার স্কচ আইসক্রিম ও ক্যারামেল ক্রাঞ্চের সাথে মেশানো এক রয়্যাল ও ঘন মিল্কশেক।",
    "price": 120,
    "category": "MILK SHAKE",
    "image": "https://drive.google.com/thumbnail?id=1OKai8uo1Hr231LRMnoUYZJ4UuMLf0f_q&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_25",
    "name": "Black currant shake",
    "nameBn": "কালো currant ঝাঁকান",
    "description": "A premium and delicious milkshake with the wonderful taste of black currant berries and thick creamy milk.",
    "descriptionBn": "ব্ল্যাক কারেন্ট বেরির অপূর্ব স্বাদ ও ঘন ক্রিমি দুধের এক প্রিমিয়াম ও মজাদার মিল্কশেক।",
    "price": 130,
    "category": "MILK SHAKE",
    "image": "https://drive.google.com/thumbnail?id=12obLNQuBDgu6ryzbJlm432IE-MhkbKU1&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_26",
    "name": "Plain lassi",
    "nameBn": "প্লেইন লস্যি",
    "description": "A traditional North Indian cold drink churned with fresh thick sour curd, sugar and ice.",
    "descriptionBn": "টাটকা ঘন টক দই, চিনি ও বরফ দিয়ে মন্থন করা ঐতিহ্যবাহী উত্তর ভারতীয় ঠান্ডা পানীয়।",
    "price": 60,
    "category": "LASSI",
    "image": "https://drive.google.com/thumbnail?id=1hO3tfJenWNWD-RGMYhBwt3Krh0OBrUgd&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_27",
    "name": "Mango lassi",
    "nameBn": "আমের লস্যি",
    "description": "A very popular and delicious Lachi made with thick curd mixed with sweet mango flavor.",
    "descriptionBn": "মিষ্টি আমের স্বাদের সাথে ঘন দইয়ের মিশ্রণে তৈরি এক অত্যন্ত জনপ্রিয় ও সুস্বাদু লাচ্ছি।",
    "price": 99,
    "category": "LASSI",
    "image": "https://drive.google.com/thumbnail?id=1m1n5TpxGGF8B5apm25cmbrKEkVzGY0WP&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_28",
    "name": "Kaju lassi",
    "nameBn": "কাজু লস্যি",
    "description": "Bata is a royal and nutritious lachi of cashew nuts and thick curd, which is very rich and delicious to eat.",
    "descriptionBn": "বাটা কাজুবাদাম এবং ঘন দইয়ের এক শাহি ও পুষ্টিকর লাচ্ছি, যা খেতে অত্যন্ত সমৃদ্ধ ও সুস্বাদু।",
    "price": 99,
    "category": "LASSI",
    "image": "https://drive.google.com/thumbnail?id=1k385B-dcJ5khKNi4G9l374n8r-N0XqQj&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_29",
    "name": "Panner Tikka",
    "nameBn": "প্যানার টিক্কা",
    "description": "Cubes of soft paneer marinated in spicy curd, cooked in a tandoor fire to create a smoky flavor.",
    "descriptionBn": "মশলাদার দইয়ে ম্যারিনেট করা নরম পনিরের কিউব, যা তন্দুরের আগুনে পুড়িয়ে স্মোকি ফ্লেভারে তৈরি করা হয়।",
    "price": 160,
    "category": "KABAB - VEG",
    "image": "https://drive.google.com/thumbnail?id=1vgkkibX1Xa6dHABes-UovT90Z8XQbbNm&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_30",
    "name": "Panner Pudina Tikka",
    "nameBn": "প্যানার পুদিনা টিক্কা",
    "description": "Tandoori baked soft paneer with fragrant mint and coriander green spices is a very tasty pada.",
    "descriptionBn": "সুগন্ধি পুদিনা ও ধনেপাতার সবুজ মশলায় মাখানো নরম পনির, তন্দুরে সেঁকা এক দারুণ সুস্বাদু পদ।",
    "price": 170,
    "category": "KABAB - VEG",
    "image": "https://drive.google.com/thumbnail?id=1ZCzNR_BeL4nKpFWUDok-ncm5ICfGNJdF&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_31",
    "name": "Alu Tikka",
    "nameBn": "আলু টিক্কা",
    "description": "Potato slices coated in special Indian spices, served crispy and smoky in the tandoor.",
    "descriptionBn": "বিশেষ ভারতীয় মশলায় মাখানো আলুর টুকরো, যা তন্দুরে পুড়িয়ে মুচমুচে ও স্মোকি করে পরিবেশন করা হয়।",
    "price": 90,
    "category": "KABAB - VEG",
    "image": "https://drive.google.com/thumbnail?id=1c8B0ZoNfKpJFq77TkVepaV825gG2G0lx&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_32",
    "name": "Tandoori Chicken (H/F)",
    "nameBn": "তন্দুরি চিকেন (H/F)",
    "description": "Whole chicken pieces marinated in traditional red tandoori spices and curd, cooked in an earthen tandoor.",
    "descriptionBn": "ঐতিহ্যবাহী লাল তন্দুরি মশলা ও দইয়ে মাখানো আস্ত মুরগির টুকরো, যা মাটির তন্দুরে পুড়িয়ে তৈরি করা হয়।",
    "price": 250,
    "category": "KABAB - NON-VEG",
    "image": "https://drive.google.com/thumbnail?id=1djg4_sUWBdCn7lmtQILRxCiJPZq58uCC&sz=w800",
    "isPopular": true,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_33",
    "name": "Tangri Kabab",
    "nameBn": "ট্যাংরি কাবাব",
    "description": "Chicken leg piece or leg joint marinated in special spices and grilled in tandoor is a very tempting kebab.",
    "descriptionBn": "মুরগির লেগ পিস বা লেগ জয়েন্ট বিশেষ মশলায় ম্যারিনেট করে তন্দুরে ঝলসানো এক অত্যন্ত লোভনীয় কাবাব।",
    "price": 220,
    "category": "KABAB - NON-VEG",
    "image": "https://drive.google.com/thumbnail?id=1gLsIo1qcfKGIX4SyzL1yGsK5CEU3H0h8&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": true
  },
  {
    "id": "item_34",
    "name": "Chicken Tikka",
    "nameBn": "চিকেন টিক্কা",
    "description": "Tender pieces of boneless chicken, marinated in Indian spices and roasted to perfection over tandoor fire.",
    "descriptionBn": "হাড়হীন মুরগির মাংসের নরম টুকরো, ভারতীয় মশলায় মাখিয়ে তন্দুরের আগুনে নিখুঁতভাবে রোস্ট করা।",
    "price": 180,
    "category": "KABAB - NON-VEG",
    "image": "https://drive.google.com/thumbnail?id=1TI2kt9M1keoGpPj0s-LU-bDxzZNszgAi&sz=w800",
    "isPopular": true,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_35",
    "name": "Malai Tikka",
    "nameBn": "মালাই টিক্কা",
    "description": "Melt-in-your-mouth tender chicken kebabs made with a mild and shahi marination of cashew batter, cream and cheese.",
    "descriptionBn": "কাজুবাদাম বাটা, ক্রিম ও চিজের এক মৃদু ও শাহি ম্যারিনেশনে তৈরি মুখে মিলিয়ে যাওয়া নরম চিকেন কাবাব।",
    "price": 200,
    "category": "KABAB - NON-VEG",
    "image": "https://drive.google.com/thumbnail?id=129CkKwLm6EmyEaq0XhQ0eOqFOvlMpDOF&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": true
  },
  {
    "id": "item_36",
    "name": "Resmi Tikka",
    "nameBn": "রেশমি টিক্কা",
    "description": "Super soft and juicy chicken kebabs like silk, made with egg, cream and mild spices.",
    "descriptionBn": "রেশমের মতো অত্যন্ত নরম ও জুসি চিকেন কাবাব, যা ডিম, ক্রিম এবং হালকা মশলায় তৈরি করা হয়।",
    "price": 220,
    "category": "KABAB - NON-VEG",
    "image": "https://drive.google.com/thumbnail?id=16N2SkMam4iUuRifhRViuJVxiLq264giu&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_37",
    "name": "Hariyali Tikka",
    "nameBn": "হরিয়ালি টিক্কা",
    "description": "Fragrant and crispy chicken kebabs coated in a green paste of fresh mint, coriander leaves and green chillies.",
    "descriptionBn": "তাজা পুদিনা, ধনেপাতা ও কাঁচালঙ্কার সবুজ পেস্টে মাখানো সুগন্ধি ও চটপটা চিকেন কাবাব।",
    "price": 190,
    "category": "KABAB - NON-VEG",
    "image": "https://drive.google.com/thumbnail?id=1UkF9PFD0ii_iOskt5QJKiLBgty5Q18_6&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_38",
    "name": "Tandoori Roti",
    "nameBn": "তন্দুরি রোটি",
    "description": "Healthy and crunchy round bread made from flour, which is baked in a clay tandoor.",
    "descriptionBn": "আটা দিয়ে তৈরি স্বাস্থ্যকর ও মুচমুচে গোল রুটি, যা মাটির তন্দুরে সেঁকা হয়।",
    "price": 12,
    "category": "BREAD",
    "image": "https://drive.google.com/thumbnail?id=1Pr4M5jiwTiE5sGCqx5ItRsiZRbstSceL&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_39",
    "name": "Plain Naan",
    "nameBn": "প্লেইন নান",
    "description": "Traditional Indian soft and light fulko tandoori bread made with flour.",
    "descriptionBn": "ময়দা দিয়ে তৈরি ঐতিহ্যবাহী ভারতীয় নরম ও হালকা ফুলকো তন্দুরি রুটি।",
    "price": 25,
    "category": "BREAD",
    "image": "https://drive.google.com/thumbnail?id=1OpPqfPI3pTGVMbU1neLbX8WgU96mYGG0&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_40",
    "name": "Butter Naan",
    "nameBn": "বাটার নান",
    "description": "A very popular and delicious naan with lots of butter brushed on hot tandoori naan.",
    "descriptionBn": "গরম তন্দুরি নানের উপর প্রচুর পরিমাণে মাখন ব্রাশ করা এক অত্যন্ত জনপ্রিয় ও সুস্বাদু নান।",
    "price": 35,
    "category": "BREAD",
    "image": "https://drive.google.com/thumbnail?id=1VV-sYcIzQbWRn_4120LNKmxxxf6MjBAx&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_41",
    "name": "Garlic Naan",
    "nameBn": "রসুন নান",
    "description": "A great tasting naan filled with butter and fragrant with crushed garlic and coriander leaves.",
    "descriptionBn": "কুচোনো রসুন ও ধনেপাতা ছড়ানো সুগন্ধি এবং মাখনে ভরা এক দুর্দান্ত স্বাদের নান।",
    "price": 45,
    "category": "BREAD",
    "image": "https://drive.google.com/thumbnail?id=1Lvf83ntu9Dbbw7msPz23uV6B_HBYadtm&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_42",
    "name": "Cheese Naan",
    "nameBn": "পনির নান",
    "description": "A soft, creamy and tempting naan bread filled with melted cheese.",
    "descriptionBn": "ভেতরে গলানো চিজের পুর ভরা এক নরম, ক্রিমি ও লোভনীয় নান রুটি।",
    "price": 50,
    "category": "BREAD",
    "image": "https://drive.google.com/thumbnail?id=1jqSVVuLwb5xF45klGdsKT54vL-upLz1C&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_43",
    "name": "Kulcha",
    "nameBn": "কুলচা",
    "description": "A special type of soft and light spongy Indian bread made from flour.",
    "descriptionBn": "ময়দা দিয়ে তৈরি এক বিশেষ ধরণের নরম ও হালকা স্পঞ্জি ভারতীয় রুটি।",
    "price": 25,
    "category": "BREAD",
    "image": "https://drive.google.com/thumbnail?id=1wKqAUaLsn-P2dMtFTH87ZcsGyPzRt_fT&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_44",
    "name": "Masala Kulcha",
    "nameBn": "মসলা কুলচা",
    "description": "A delicious and filling kulcha filled with crisp spicy potatoes and cheese.",
    "descriptionBn": "চটপটা মশলাদার আলু ও পনিরের পুর ভরা সুস্বাদু এবং ভরপুর এক কুলচা।",
    "price": 50,
    "category": "BREAD",
    "image": "https://drive.google.com/thumbnail?id=1t6UjvRCMEapSeY7bYFPkK4Xj44HKMWUT&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_45",
    "name": "Alu Parata",
    "nameBn": "আলু পরাটা",
    "description": "Tandoori baked or tawa fried traditional delicious parathas made with spicy potato filling.",
    "descriptionBn": "মশলাদার আলুর পুর দিয়ে তৈরি তন্দুরে সেঁকা বা তাওয়ায় ভাজা ঐতিহ্যবাহী সুস্বাদু পরাঠা।",
    "price": 50,
    "category": "BREAD",
    "image": "https://drive.google.com/thumbnail?id=1TsaeCA9K_pJmA1O-w6U_iIqKOpzQC7QJ&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_46",
    "name": "Paneer Butter Masala",
    "nameBn": "পনির বাটার মসলা",
    "description": "A shahi pada of soft cheese in a sweet-salty thick gravy of tomatoes and cashews made with butter and cream.",
    "descriptionBn": "মাখন ও ক্রিম দিয়ে তৈরি টমেটো ও কাজুর মিষ্টি-নোনতা ঘন গ্রেভিতে নরম পনিরের এক শাহি পদ।",
    "price": 180,
    "category": "GRAVY - VEG",
    "image": "https://drive.google.com/thumbnail?id=1MHcwX4Y_E7e7bUogIgAJnUy1yKvi-XhG&sz=w800",
    "isPopular": false,
    "isBestSeller": true,
    "isHighestRated": false
  },
  {
    "id": "item_47",
    "name": "Mix Veg",
    "nameBn": "মিক্স ভেজ",
    "description": "A delicious and nutritious Indian spicy curry made with a variety of fresh seasonal vegetables.",
    "descriptionBn": "বিভিন্ন ধরণের টাটকা মরশুমি সবজি দিয়ে তৈরি এক সুস্বাদু এবং পুষ্টিকর ভারতীয় মশলাদার তরকারি।",
    "price": 110,
    "category": "GRAVY - VEG",
    "image": "https://drive.google.com/thumbnail?id=1FavWwJA3imOY9KPAV_hk4aDadL6yxXSq&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_48",
    "name": "Veg Kolapuri",
    "nameBn": "ভেজ কোলাপুরি",
    "description": "Authentic Indian spices and red chilli slaw and crisp vegetable pad made in Maharashtra's Kolapuri style.",
    "descriptionBn": "মহারাষ্ট্রের কোলাপুরি স্টাইলে তৈরি খাঁটি ভারতীয় মশলা ও লাল লঙ্কার ঝাল ও চটপটা সবজির পদ।",
    "price": 120,
    "category": "GRAVY - VEG",
    "image": "https://drive.google.com/thumbnail?id=1F1T04QqTywVCZ3aA1tK-PCspGOSGtQ7a&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_49",
    "name": "Kadai Veg",
    "nameBn": "কড়াই ভেজ",
    "description": "A wonderful pada cooked with kadai masala, capsicum, onion and fresh vegetables.",
    "descriptionBn": "কড়াই মশলা, ক্যাপসিকাম, পেঁয়াজ এবং টাটকা সবজি দিয়ে কষিয়ে রান্না করা এক দুর্দান্ত পদ।",
    "price": 130,
    "category": "GRAVY - VEG",
    "image": "https://drive.google.com/thumbnail?id=1Cqs69R56ZJlDEUyJW0XRbdAD5GHATzVX&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_50",
    "name": "Paneer Tikka Masala",
    "nameBn": "পনির টিক্কা মসলা",
    "description": "Tandoori grilled smoky paneer tikka pieces cooked in a thick and spicy gravy.",
    "descriptionBn": "তন্দুরে পোড়ানো স্মোকি পনির টিক্কা টুকরোগুলি ঘন ও মশলাদার চটপটা গ্রেভিতে রান্না করা হয়।",
    "price": 200,
    "category": "GRAVY - VEG",
    "image": "https://drive.google.com/thumbnail?id=1Zn7ikNbqT7Fohl-UNTOOkvl0FmPeMHZy&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_51",
    "name": "Kadai Paneer",
    "nameBn": "কদই পনির",
    "description": "A very popular and delicious dish of paneer with kadai masala, diced onion and capsicum.",
    "descriptionBn": "কড়াই মশলা, ডুমো করে কাটা পেঁয়াজ ও ক্যাপসিকামের সাথে পনিরের এক অত্যন্ত জনপ্রিয় ও সুস্বাদু পদ।",
    "price": 180,
    "category": "GRAVY - VEG",
    "image": "https://drive.google.com/thumbnail?id=1AJ8pGNw8FcPr925IlCUa0dv2xXB-M1my&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_52",
    "name": "Chicken Tikka Masala",
    "nameBn": "চিকেন টিক্কা মসলা",
    "description": "Tandoori seared boneless chicken tikka pieces cooked in thick, crispy and aromatic spicy gravy.",
    "descriptionBn": "তন্দুরে ঝলসানো বোনলেস চিকেন টিক্কার টুকরো ঘন, চটপটা এবং সুগন্ধি মশলাদার গ্রেভিতে রান্না করা পদ।",
    "price": 180,
    "category": "GRAVY - NON-VEG",
    "image": "https://drive.google.com/thumbnail?id=1q0bBFrGjDe9QrLr4asZxmzKk_qtOZLT-&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_53",
    "name": "Butter Chicken Masala",
    "nameBn": "বাটার চিকেন মসলা",
    "description": "Tandoori chicken pieces cooked in a sweet and mild shahi gravy of butter, cream and tomatoes is a world famous dish.",
    "descriptionBn": "তন্দুরি চিকেনের টুকরো মাখন, ক্রিম এবং টমেটোর মিষ্টি ও মৃদু শাহি গ্রেভিতে রান্না করা বিশ্বখ্যাত পদ।",
    "price": 240,
    "category": "GRAVY - NON-VEG",
    "image": "https://drive.google.com/thumbnail?id=1Qt68AH_GPTxRPsIsZMjYHaREGNY6VLS2&sz=w800",
    "isPopular": true,
    "isBestSeller": true,
    "isHighestRated": false
  },
  {
    "id": "item_54",
    "name": "Resmi Chicken Masala",
    "nameBn": "রেসমি চিকেন মসলা",
    "description": "Soft silky kebab pieces served in a rich and mildly spicy gravy of cream and cashew nuts.",
    "descriptionBn": "নরম রেশমি কাবাব টুকরোগুলি ক্রিম ও কাজুবাদামের এক সমৃদ্ধ এবং হালকা মশলাদার গ্রেভিতে পরিবেশিত হয়।",
    "price": 200,
    "category": "GRAVY - NON-VEG",
    "image": "https://drive.google.com/thumbnail?id=1pAuC3AR70yhsrXA25sWwdjOVDSndP9Se&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_55",
    "name": "Kadai Chicken",
    "nameBn": "কদই চিকেন",
    "description": "Chicken marinated with curry spices, capsicum and onion made with fresh coriander and dry chilli tails.",
    "descriptionBn": "টাটকা ধনে ও শুকনো লঙ্কা টেলে তৈরি কড়াই মশলা, ক্যাপসিকাম ও পেঁয়াজের সাথে কষানো চিকেন।",
    "price": 210,
    "category": "GRAVY - NON-VEG",
    "image": "https://drive.google.com/thumbnail?id=1VEPlQhSZnI6frvHlcM7wkohZWuAO4TKi&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_56",
    "name": "Chicken Kolapuri",
    "nameBn": "চিকেন কোলাপুরি",
    "description": "Kolapuri is a spicy, red and very juicy South West Indian chicken dish cooked in spices.",
    "descriptionBn": "কোলাপুরি মশলায় রান্না করা ঝাল, লাল ও অত্যন্ত চটপটা এক দক্ষিণ-পশ্চিম ভারতীয় চিকেনের পদ।",
    "price": 200,
    "category": "GRAVY - NON-VEG",
    "image": "https://drive.google.com/thumbnail?id=1rZPw4t_mgs1KKwkiSJoyrNslo-R3k8h6&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_57",
    "name": "Chicken Do pyaza",
    "nameBn": "চিকেন ডো প্যাজা",
    "description": "A delicious, mildly sweet and spicy chicken gravy made by using onions twice in the cooking.",
    "descriptionBn": "রান্নায় দু'বার বিভিন্নভাবে পেঁয়াজ ব্যবহার করে তৈরি হালকা মিষ্টি ও মশলাদার এক সুস্বাদু চিকেন গ্রেভি।",
    "price": 190,
    "category": "GRAVY - NON-VEG",
    "image": "https://drive.google.com/thumbnail?id=1Xt11zr1119qwrGMWsrzjgnHmfXK2ielm&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_58",
    "name": "Chicken Handi",
    "nameBn": "চিকেন হান্ডি",
    "description": "Creamy and fragrant chicken drumsticks slow cooked in a traditional pot or handi style.",
    "descriptionBn": "ঐতিহ্যবাহী হাঁড়িতে বা হান্ডি স্টাইলে ধীমে আঁচে রান্না করা ক্রিমি এবং সুগন্ধি চিকেনের পদ।",
    "price": 210,
    "category": "GRAVY - NON-VEG",
    "image": "https://drive.google.com/thumbnail?id=1KLnDdJ1CP17QMIUcg5Ha7HXQenUmNpGl&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_59",
    "name": "Chicken Kasha",
    "nameBn": "চিকেন কাশা",
    "description": "Delicious dark colored chicken cooked in authentic Bengali style with onion, ginger, garlic and mustard oil.",
    "descriptionBn": "খাঁটি বাঙালি স্টাইলে পেঁয়াজ, আদা, রসুন ও সর্ষের তেলে কষিয়ে রান্না করা গাঢ় রঙের সুস্বাদু চিকেন।",
    "price": 160,
    "category": "GRAVY - NON-VEG",
    "image": "https://drive.google.com/thumbnail?id=1pMqMrQPRLs4N7r0dXoCgae6sc5dCB0Cj&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_60",
    "name": "Chicken Curry",
    "nameBn": "চিকেন কারি",
    "description": "A hearty and easy-to-digest chicken curry cooked in a home-style broth of potatoes and mild spices.",
    "descriptionBn": "ঘরোয়া স্টাইলে আলু ও হালকা মশলার ঝোলে রান্না করা এক তৃপ্তিদায়ক এবং সহজপাচ্য চিকেন কারি।",
    "price": 150,
    "category": "GRAVY - NON-VEG",
    "image": "https://drive.google.com/thumbnail?id=1xqiTq9b6DQLzyfkr8NdP3j3tu5p0CLWe&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_61",
    "name": "Hot Coffee",
    "nameBn": "গরম কফি",
    "description": "A smoky energetic and fresh drink made with a blend of hot milk and pure coffee beans.",
    "descriptionBn": "গরম দুধ এবং খাঁটি কফি বিনসের ব্লেন্ডে তৈরি এক ধোঁয়া ওঠা এনার্জিটিক ও ফ্রেশ পানীয়।",
    "price": 45,
    "category": "COFFEE",
    "image": "https://drive.google.com/thumbnail?id=1FAp4kKb4lgcOpHHG9iysH4NX6DsS9KSh&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_62",
    "name": "Black Coffee",
    "nameBn": "ব্ল্যাক কফি",
    "description": "Strong and aromatic coffee made without milk, which instantly relieves fatigue and restores energy.",
    "descriptionBn": "দুধ ছাড়া তৈরি কড়া ও সুগন্ধি কফি, যা নিমেষেই ক্লান্তি দূর করে এনার্জি ফিরিয়ে আনে।",
    "price": 30,
    "category": "COFFEE",
    "image": "https://drive.google.com/thumbnail?id=1P8Tgy5Qbg1Kbc5aFKk3_nikrHkcOzhpq&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_63",
    "name": "Cold Coffee",
    "nameBn": "কোল্ড কফি",
    "description": "A creamy and sweet refreshing cold coffee drink made with a blend of ice, cold milk and coffee.",
    "descriptionBn": "বরফ, ঠান্ডা দুধ এবং কফির ব্লেন্ডে তৈরি এক ক্রিমি ও মিষ্টি সতেজকারী ঠান্ডা কফি পানীয়।",
    "price": 99,
    "category": "COFFEE",
    "image": "https://drive.google.com/thumbnail?id=1J7a_Ek4VAc8j3zyqa1gkEK7K2EcjpVC2&sz=w800",
    "isPopular": true,
    "isBestSeller": true,
    "isHighestRated": false
  },
  {
    "id": "item_64",
    "name": "Cold Coffee with Ice-cream",
    "nameBn": "আইসক্রিমের সাথে কোল্ড কফি",
    "description": "A scoop of vanilla or chocolate ice cream over cold coffee is a premium and royal drink.",
    "descriptionBn": "কোল্ড কফির উপরে ভ্যানিলা বা চকোলেট আইসক্রিমের স্কুপ দেওয়া এক প্রিমিয়াম ও রয়্যাল পানীয়।",
    "price": 130,
    "category": "COFFEE",
    "image": "https://drive.google.com/thumbnail?id=1VZMflCHItEHheURau2iGNokptsh_CqQI&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": true
  },
  {
    "id": "item_65",
    "name": "Veg Clear",
    "nameBn": "ভেজ ক্লিয়ার",
    "description": "Fresh vegetables are boiled in light and healthy clear broth, which is very beneficial for health.",
    "descriptionBn": "টাটকা সবজি সেদ্ধ করা হালকা এবং স্বাস্থ্যকর ক্লিয়ার ব্রথ, যা স্বাস্থ্যের জন্য অত্যন্ত উপকারী।",
    "price": 40,
    "category": "SOUP",
    "image": "https://drive.google.com/thumbnail?id=1Crptmo75oeWBmevGyb2CeB3THBN17fbr&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_66",
    "name": "Veg manchow",
    "nameBn": "ভেজ মাঞ্চো",
    "description": "A Chinese style soup flavored with garlic, ginger and soy sauce, topped with deep fried noodles.",
    "descriptionBn": "রসুন, আদা ও সয়া সসের স্বাদে ভরপুর এক চাইনিজ স্টাইল সুপ, যার উপরে মুচমুচে ফ্রাইড নুডলস দেওয়া হয়।",
    "price": 59,
    "category": "SOUP",
    "image": "https://drive.google.com/thumbnail?id=1EnppE0Eu6hHE3s7IEUaXa_QPbaNGCQrd&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_67",
    "name": "Hot & Sour Veg",
    "nameBn": "গরম ও টক সবজি",
    "description": "A delicious soup made with vegetables, vinegar and chilies that tastes salty and sour at the same time.",
    "descriptionBn": "সবজি, ভিনিগার ও লঙ্কার সমন্বয়ে তৈরি এক একই সাথে ঝাল এবং টক স্বাদের মুখরোচক সুপ।",
    "price": 59,
    "category": "SOUP",
    "image": "https://drive.google.com/thumbnail?id=1kBeiP86UTeDyctlwyqsEKDVsT26uZKmE&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_68",
    "name": "Chicken Clear",
    "nameBn": "চিকেন ক্লিয়ার",
    "description": "A light, nutritious and comforting hot soup made with chicken and vegetable extracts.",
    "descriptionBn": "মুরগির মাংস ও সবজির নির্যাস দিয়ে তৈরি এক হালকা, পুষ্টিকর এবং আরামদায়ক গরম সুপ।",
    "price": 59,
    "category": "SOUP",
    "image": "https://drive.google.com/thumbnail?id=1rGpEEAwJN_91yBLnD_ondwFfphmqirT3&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_69",
    "name": "Chicken Manchow",
    "nameBn": "চিকেন মাঞ্চো",
    "description": "Scalloped and spicy Chinese soup made with crispy chicken and vegetables, with crunchy fried noodles.",
    "descriptionBn": "কুচোনো চিকেন ও সবজি দিয়ে তৈরি ঝাল ও চটপটা চাইনিজ সুপ, সাথে ক্রাঞ্চি ভাজা নুডলস।",
    "price": 85,
    "category": "SOUP",
    "image": "https://drive.google.com/thumbnail?id=1adRcIhs9vEakyQxbUFJ1mt90KFxUKtmV&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_70",
    "name": "Hot & Soup Chicken",
    "nameBn": "গরম ও স্যুপ চিকেন",
    "description": "A classic and warming Chinese soup with sour and salty flavor with chicken pieces.",
    "descriptionBn": "চিকেন টুকরো সম্বলিত টক ও ঝাল স্বাদের এক ক্লাসিক এবং শরীর গরম করা চাইনিজ সুপ।",
    "price": 90,
    "category": "SOUP",
    "image": "https://drive.google.com/thumbnail?id=1mvBJ13FwwShWPREAwTf7shBcEmyRwbuU&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_71",
    "name": "French Fry",
    "nameBn": "ফ্রেঞ্চ ফ্রাই",
    "description": "Potatoes cut into long pieces and deep fried in oil are world famous and everyone's favorite snacks.",
    "descriptionBn": "আলু লম্বা করে কেটে ডুবোতেলে সোনালি ও মুচমুচে করে ভাজা বিশ্বখ্যাত এবং সবার প্রিয় স্ন্যাকস।",
    "price": 90,
    "category": "SNACKS",
    "image": "https://drive.google.com/thumbnail?id=1EjAK9YZBZTq7epiUtXmPicGH3Kts0cT6&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_72",
    "name": "Crispy Wings",
    "nameBn": "ক্রিস্পি উইংস",
    "description": "Juicy chicken wings deep fried with special spices and batter coating.",
    "descriptionBn": "বিশেষ মশলা ও ব্যাটারের কোটিং দিয়ে মুচমুচে করে ভাজা জুসি চিকেন উইংস বা ডানার অংশ।",
    "price": 130,
    "category": "SNACKS",
    "image": "https://drive.google.com/thumbnail?id=1MN0xofJ_vVU0Jr9x0p8eZ3LcMpuOL7CI&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_73",
    "name": "Hot Chili Wings",
    "nameBn": "হট চিলি উইংস",
    "description": "Crispy Pads made by tossing deep fried chicken wings with a slaw and sweet chili sauce and garlic.",
    "descriptionBn": "মুচমুচে ভাজা চিকেন উইংসকে ঝাল ও মিষ্টি চিলি সস এবং রসুনের সাথে টস করে তৈরি চটপটা পদ।",
    "price": 240,
    "category": "SNACKS",
    "image": "https://drive.google.com/thumbnail?id=1ymsyZFWil4RhjJDgqMTDJeCxFtPLEVaW&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_74",
    "name": "Fried Chicken (8 pcs)",
    "nameBn": "ভাজা চিকেন (8 পিসি)",
    "description": "8 large fried pieces of crispy outside and soft juicy inside chicken, perfect for sharing with family or friends.",
    "descriptionBn": "বাইরে ক্রিস্পি ও ভেতরে নরম জুসি চিকেনের ৮টি বড় ভাজা টুকরো, পরিবার বা বন্ধুদের সাথে শেয়ার করার জন্য সেরা।",
    "price": 220,
    "category": "SNACKS",
    "image": "https://drive.google.com/thumbnail?id=1VmudjovHS57AZ2v3qOmsWkZnDa_JlIsk&sz=w800",
    "isPopular": true,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_75",
    "name": "Fried Chicken (4 pcs)",
    "nameBn": "ভাজা মুরগি (4 পিসি)",
    "description": "4 fried pieces of tender and juicy chicken in a golden coating.",
    "descriptionBn": "মুচমুচে সোনালি আবরণের ভেতর নরম ও রসালো চিকেনের ৪টি ভাজা টুকরো।",
    "price": 120,
    "category": "SNACKS",
    "image": "https://drive.google.com/thumbnail?id=1VmudjovHS57AZ2v3qOmsWkZnDa_JlIsk&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_76",
    "name": "Drums of Heaven (4pcs)",
    "nameBn": "ড্রামস অফ হেভেন (4pcs)",
    "description": "The Lollipop Style Chicken Wings are lightly fried and slathered in a sweet chili-garlic sauce that tastes heavenly.",
    "descriptionBn": "ললিপপ স্টাইলের চিকেন উইংস মুচমুচে করে ভেজে ঝাল ও মিষ্টি চিলি-গার্লিক সসে মাখানো এক স্বর্গীয় স্বাদ।",
    "price": 260,
    "category": "SNACKS",
    "image": "https://drive.google.com/thumbnail?id=1kkyEOzyOVsuymwiOqKn_JxzZrbcKCBFg&sz=w800",
    "isPopular": true,
    "isBestSeller": true,
    "isHighestRated": false
  },
  {
    "id": "item_77",
    "name": "Drums of Heaven (2pcs)",
    "nameBn": "ড্রামস অফ হেভেন (2 পিসি)",
    "description": "2 tempting slices of delicious and juicy Drums of Heaven tossed in Chili-Garlic Sauce.",
    "descriptionBn": "চিলি-গার্লিক সসে টস করা সুস্বাদু ও জুসি ড্রামস অফ হেভেনের ২টি লোভনীয় টুকরো।",
    "price": 130,
    "category": "SNACKS",
    "image": "https://drive.google.com/thumbnail?id=1kkyEOzyOVsuymwiOqKn_JxzZrbcKCBFg&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_78",
    "name": "Black Paper Chicken",
    "nameBn": "ব্ল্যাক পেপার চিকেন",
    "description": "A saucy and delicious chicken pada made with the pungent aroma of freshly ground chillies, garlic and soy sauce.",
    "descriptionBn": "তাজা গুঁড়ো করা গোলমরিচ, রসুন ও সয়া সসের কড়া সুবাসে তৈরি এক ঝাল ও সুস্বাদু চিকেন পদ।",
    "price": 170,
    "category": "SNACKS",
    "image": "https://drive.google.com/thumbnail?id=1ai662HNvvs_3ezKn_CIK_38fqwwdXdh0&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_79",
    "name": "Chicken Antasiya (Leg 3pcs)",
    "nameBn": "চিকেন আন্তাসিয়া (লেগ 3 পিসি)",
    "description": "An exquisite fried snack of 3 whole chicken leg pieces prepared with our special secret spices and marination.",
    "descriptionBn": "আমাদের বিশেষ সিক্রেট মশলা ও ম্যারিনেশনে তৈরি ৩টি আস্ত চিকেন লেগ পিসের এক অনবদ্য ফ্রাইড স্ন্যাকস।",
    "price": 220,
    "category": "SNACKS",
    "image": "https://drive.google.com/thumbnail?id=1XZRNTQGzmf7l_JKrkNNyWlbNfxtZbyKb&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_80",
    "name": "Fish Finger (8 pcs)",
    "nameBn": "ফিশ ফিঙ্গার (8 পিসি)",
    "description": "Long pieces of boneless fish fillet rolled in breadcrumbs and fried until golden brown are delicious snacks.",
    "descriptionBn": "কাঁটাহীন মাছের ফিলের লম্বা টুকরো ব্রেডক্রাম্বে গড়িয়ে মুচমুচে সোনালি করে ভাজা মুখরোচক স্ন্যাকস।",
    "price": 200,
    "category": "SNACKS",
    "image": "https://drive.google.com/thumbnail?id=1ykUbzmqX7X2e6A6fXPafWgaDhDAa9c4Q&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_81",
    "name": "Chicken Popcorn",
    "nameBn": "চিকেন পপকর্ন",
    "description": "Chunky and Spicy Boneless Fried Chicken Bites made in small bite sizes that melt in your mouth.",
    "descriptionBn": "ছোট ছোট কামড়ের মাপে তৈরি মুচমুচে ও মশলাদার বোনলেস ফ্রাইড চিকেন বাইটস, যা মুখে দিলেই মিলিয়ে যায়।",
    "price": 90,
    "category": "SNACKS",
    "image": "https://drive.google.com/thumbnail?id=1XyVYY7deBeXgEIz6IStOOAuRUtGVf3Js&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_82",
    "name": "Chicken Fingers (10pcs)",
    "nameBn": "চিকেন ফিঙ্গারস (10 পিসি)",
    "description": "Boneless chicken strips deep fried in batter and breadcrumbs 10 long and delicious snacks.",
    "descriptionBn": "বোনলেস চিকেন স্ট্রিপ্স মুচমুচে ব্যাটার ও ব্রেডক্রাম্বে ভেজে তৈরি ১০টি লম্বা ও সুস্বাদু স্ন্যাকস।",
    "price": 220,
    "category": "SNACKS",
    "image": "https://drive.google.com/thumbnail?id=13CwThYY5i5dia4vzyFv4DLpY0Uj6jsjy&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_83",
    "name": "Chicken Fingers (5pc)",
    "nameBn": "চিকেন ফিঙ্গারস (5 পিসি)",
    "description": "5 delicious pieces of crispy and golden fried boneless chicken fingers, slathered with sauce.",
    "descriptionBn": "ক্রিস্পি ও গোল্ডেন ভাজা বোনলেস চিকেন ফিঙ্গারের ৫টি মুখরোচক টুকরো, সসের সাথে দারুণ জমজমাট।",
    "price": 110,
    "category": "SNACKS",
    "image": "https://drive.google.com/thumbnail?id=1MSYe9KdQ9LRGu9GpqwPVzB3yMZiAkyHQ&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_84",
    "name": "Chicken Lolipop",
    "nameBn": "চিকেন ললিপপ",
    "description": "Chicken wing meat is gathered on one side and shaped like a lollipop and deep fried in a spicy batter.",
    "descriptionBn": "মুরগির ডানার মাংস একপাশে জড়ো করে ললিপপের আকার দিয়ে মশলাদার ব্যাটারে মুচমুচে করে ভাজা পদ।",
    "price": 140,
    "category": "SNACKS",
    "image": "https://drive.google.com/thumbnail?id=1UMEOMCpxQhMilfdh1EculhpzoZF9KjaX&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_85",
    "name": "Roasted Chicken Fry (leg 3)",
    "nameBn": "রোস্টেড চিকেন ফ্রাই (লেগ ৩)",
    "description": "3 juicy and flavorful chicken leg pieces lightly fried after roasting in special spices.",
    "descriptionBn": "বিশেষ মশলায় রোস্ট করার পর হালকা ভেজে নেওয়া ৩টি জুসি ও ফ্লেভারফুল চিকেন লেগ পিস।",
    "price": 180,
    "category": "SNACKS",
    "image": "https://drive.google.com/thumbnail?id=1Yg426wER9aoVAatftiTRJBFFJHCEk6Nf&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_86",
    "name": "Crispy Chilli Babycorn",
    "nameBn": "ক্রিস্পি চিলি বেবিকর্ন",
    "description": "Baby corn crumbles and tossed in sauteed onions, green chilies and Chinese chili sauce make a great veggie snack.",
    "descriptionBn": "কচি বেবিকর্ন মুচমুচে করে ভেজে পেঁয়াজ, কাঁচালঙ্কা এবং চাইনিজ চিলি সসে টস করা এক দুর্দান্ত ভেজ স্ন্যাকস।",
    "price": 140,
    "category": "SNACKS",
    "image": "https://drive.google.com/thumbnail?id=1vf0-ieT_o__B2p6ihyQuh_3G9Bz61b6m&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_87",
    "name": "Green salad",
    "nameBn": "সবুজ সালাদ",
    "description": "Healthy and refreshing salad garnished with fresh cucumber, tomato, onion, carrot and lemon slices.",
    "descriptionBn": "টাটকা শসা, টমেটো, পেঁয়াজ, গাজর এবং লেবুর টুকরো দিয়ে সাজানো স্বাস্থ্যকর ও সতেজ সালাদ।",
    "price": 40,
    "category": "SALAD",
    "image": "https://drive.google.com/thumbnail?id=1QEmVDToKyB2OEl33NVxtFH4eP1DM8NFY&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_88",
    "name": "Onion Salad",
    "nameBn": "পেঁয়াজ সালাদ",
    "description": "A crisp Indian salad topped with diced onions, green chillies, lemon juice and chaat masala.",
    "descriptionBn": "গোল করে কাটা পেঁয়াজ, কাঁচালঙ্কা, লেবুর রস ও চাট মশলা ছড়ানো চটপটা ভারতীয় সালাদ।",
    "price": 25,
    "category": "SALAD",
    "image": "https://drive.google.com/thumbnail?id=1biXjo3Q49aCNvjcQRiiAuNKRpDLds0nZ&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_89",
    "name": "Hawayein Chicken Salad",
    "nameBn": "হাওয়ায়েন চিকেন সালাদ",
    "description": "An exotic salad with boiled or roasted chicken pieces, pineapple and fresh vegetables tossed in a creamy dressing.",
    "descriptionBn": "সেদ্ধ বা রোস্ট করা চিকেন টুকরো, আনারস এবং টাটকা সবজির সাথে ক্রিমি ড্রেসিংয়ে মাখানো এক এক্সটিক সালাদ।",
    "price": 130,
    "category": "SALAD",
    "image": "https://drive.google.com/thumbnail?id=1wTF4-MM4_v6S4ZSk6sKGd15RWQblhf82&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_90",
    "name": "Chicken Shawarma Wrap",
    "nameBn": "চিকেন শাওয়ারমা মোড়ানো",
    "description": "A popular Middle Eastern dish of roasted and fried spicy chicken, salad and creamy mayonnaise or garlic sauce wrapped in soft bread.",
    "descriptionBn": "রোস্টেড ও কুচোনো মশলাদার চিকেন, সালাদ এবং ক্রিমি মেয়োনিজ বা গার্লিক সস নরম রুটিতে মোড়ানো এক মধ্যপ্রাচ্যের জনপ্রিয় পদ।",
    "price": 120,
    "category": "SHAWARMA",
    "image": "https://drive.google.com/thumbnail?id=1z_AcEXjsZFTu5ub3zcO27d-Zymp-3f4W&sz=w800",
    "isPopular": true,
    "isBestSeller": true,
    "isHighestRated": false
  },
  {
    "id": "item_91",
    "name": "With Schezwan Souce",
    "nameBn": "শেজওয়ান সোসের সাথে",
    "description": "A great fusion of traditional chicken shawarma with spicy and tangy Chinese Szechuan sauce.",
    "descriptionBn": "ঐতিহ্যবাহী চিকেন শাওয়ারমার সাথে ঝাল ও চটপটা চাইনিজ সেজোয়ান সসের এক দুর্দান্ত ফিউশন।",
    "price": 130,
    "category": "SHAWARMA",
    "image": "https://drive.google.com/thumbnail?id=1Xdu4l3c-pzYbGPIPIJbmcVi1Pyi95TJB&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  },
  {
    "id": "item_92",
    "name": "Spl. Shawarma",
    "nameBn": "Spl. শওয়ারমা",
    "description": "Our richest and heaviest special shawarma made with extra chicken, extra cheese, special sauce and salad.",
    "descriptionBn": "অতিরিক্ত চিকেন, এক্সট্রা চিজ, বিশেষ সস এবং সালাদ দিয়ে তৈরি আমাদের সবথেকে সমৃদ্ধ এবং হেভি স্পেশাল শাওয়ারমা।",
    "price": 150,
    "category": "SHAWARMA",
    "image": "https://drive.google.com/thumbnail?id=1ExzedjKO5N59RXVC3awmdFDmUGsYqhSr&sz=w800",
    "isPopular": false,
    "isBestSeller": false,
    "isHighestRated": false
  }
];
